### ISSUE TITLE
Imposible to import { actions } from module

### ISSUE THREAD

**Issue by evilj0e** [auru/redux-unity-router#14]
`import { actions } from 'redux-unity-router';` and `import actions from 'redux-unity-router/actions';` both have `undefined` value. Seems that these modules don't exports properly.

**Comment by TimeRaider** [comment]
partially fixed in 00857ba1ce8714ee83038813a0c76cbc240bf852
`import actions from 'redux-unity-router/actions'` most likely shill won't work
