### ISSUE TITLE
history packages

### ISSUE THREAD

**Issue by Blackheart340** [auru/redux-unity-router#36]
@TimeRaider Hey, fellow. 

We're using `history` package and two days ago was published new version `4.6.0`.
And we've caught side effect linked with that. 
We had components:
```
<Link to={{ id: 'Page', query: { paths: '/some/path' } }} />
```
And expected to get url `/page?path=%2Fsome%2Fpath`. But after patch we've got string like `/page?path=%252Fsome%252Fpath`. It's happening 'cause we're escaping string twice. 

I thought the fastest solution would be fix version of that package on `4.5.1`, but I don't think it's a good way. 
Or we can remove escaping from our component, I mean <Link />.

It's up to you.

**Comment by TimeRaider** [comment]
@Blackheart340 let's fix it in our component
